### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by pntt3011** [SerialLain3170/KawaiiGenerator#1]
Thank you for your wonderful work! I'm looking for this for a long time. However, I can't find the pretrained model. I can't run the docker image either, maybe because my laptop doesn't have a NVIDIA GPU. Could you release the pretrained model so I can try it on Google Colab?

**Comment by SerialLain3170** [comment]
Thank you for the issue and I am sorry for the VERY late answer.

I will release the pretrained model in the near future so that everyone can try my application. Since I checked that GUI application can run on CPU (though the speed of inference was slower than GPU...), you may run this application on your own PC.

**Comment by pntt3011** [comment]
Thank you for your reply! 

I have rechecked the GUI app in docker. The gui_client and gui_server always exit with code 1.
The gui_server cannot find the checkpoint at './ckpts/encoder_160001.pt' so I can wait for you to release it.
As for the gui_client, this is its log:
```
app is starting...!
app is starting...!
app is starting...!

: not foundent.sh: 2: ./start_client.sh:
sleep: invalid time interval '30\r'
Try 'sleep --help' for more information.
: not foundent.sh: 4: ./start_client.sh:
)is not in GOROOT (/usr/local/go/src/client/main.go
: not foundent.sh: 2: ./start_client.sh:
sleep: invalid time interval '30\r'
Try 'sleep --help' for more information.
: not foundent.sh: 4: ./start_client.sh:
)is not in GOROOT (/usr/local/go/src/client/main.go
: not foundent.sh: 2: ./start_client.sh:
sleep: invalid time interval '30\r'
Try 'sleep --help' for more information.
: not foundent.sh: 4: ./start_client.sh:
)is not in GOROOT (/usr/local/go/src/client/main.go
```
I use dos2linux to convert start_client.sh and build.sh to unix end-of-line format and it works now. I will close this issue.
